zookeeper:
  image: epambigdata/zookeeper
  ports: 
    - "2181"
kafka:
  image: epambigdata/kafka
  ports:
    - "9092"
  links: 
    - zookeeper
  environment:
    KAFKA_ADVERTISED_HOSTNAME: "192.168.0.12"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
